import tmdbApi from "../../api/tmdbApi"; // Certifique-se de que esses imports estão corretos
import omdbApi from "../../api/omdbApi";

const processarLote = async () => {
  const filmes = [
    "No Limite do Amanhã",
    "Horas Decisivas",
    "Poder sem Limites",
    "Nunca Diga seu Nome",
    "Tinha que ser ele?",
    "Baywatch S.O.S",
    "A Autópsia",
    "Antes Que eu Vá",
    "Simplismente Acontece",
    "Sem Saída",
    "Cidade De Papel",
    "Dormindo com as Outras Pessoas",
    "O Grande Herói",
    "13horas: Soldados Secretos De Benghazi",
    "Uma noite de crime 1",
    "Uma noite de crime 2",
    "Uma noite de crime 3",
    "Soldado Anônimo",
    "Tracers",
    "Pelas garotas e pela glória",
    "Eu te amo Beth Cooper",
    "Transformers",
    "Transformers 2",
    "Transformers 3",
    "Transformers 4",
    "Transformers 5",
    "A Mala e os Errantes",
    "Felon",
    "Projeto Almanaque",
    "O Espaço Entre Nós",
    "Passageiros",
    "Cherry",
    "A Acompanhante",
    "Finalmente 18",
    "Fica Comigo",
    "Tirando o Atraso",
    "Rota de Fuga",
    "O Sequestro do Metrô 123",
    "50%",
    "Caçadores de Emoção: Além do Limite",
    "Triplo XXX",
    "O seu Jeito de Andar",
    "Corrente do Mal",
    "A Mentira",
    "Fenômenos paranormais 1",
    "Fenômenos paranormais 2",
    "Doce Vingança 1",
    "Doce Vingança 2",
    "Doce Vingança 3",
    "Aguas rasas",
    "Invencível",
    "Atividade Paranormal 1",
    "Atividade Paranormal 2",
    "Atividade Paranormal 3",
    "Atividade Paranormal 4",
    "Atividade Paranormal 5",
    "Palhaços Infernais",
    "Velozes e Furiosos 1-8",
    "A Forca",
    "Tropa de elite",
    "Tropa de elite 2",
    "Sem Escalas",
    "Poltergeist: O Fenômeno",
    "O garoto da casa ao lado",
    "Garota Infernal",
    "O Chamado",
    "O chamado 3",
    "A entidade 2",
    "Gamer",
    "O Exorcismo de Emily Rose",
    "Mad Max: Estrada da Fúria",
    "Karate Kid",
    "Furia de Titãs",
    "Furia de Titãs 2",
    "Battleship",
    "O Protetor",
    "Independence Day 2",
    "O Ataque",
    "Esquadrão Classe A",
    "X-Men: Primeira Classe",
    "Esqueceram de Mim 1",
    "Esqueceram de Mim 2",
    "Sem Dor Sem Ganho",
    "Interestelar",
    "Colegiais em Apuros",
    "Como eu era antes de você",
    "Ela é demais pra mim",
    "Ted 1",
    "Ted 2",
    "Maze Runner 1",
    "Maze Runner 2",
    "Harry Potter e a Pedra Filosofal",
    "Harry Potter e a Câmara Secreta",
    "Harry Potter e o Prisioneiro de Azkaban",
    "Harry Potter e o Cálice de Fogo",
    "Harry Potter e a Ordem da Fênix",
    "Harry Potter e o Enigma do Príncipe",
    "Harry Potter e as Relíquias da Morte – Parte 1",
    "Harry Potter e as Relíquias da Morte – Parte 2",
    "Blue Mountain State",
    "Um Geek Encantador",
    "Homem Aranha 1",
    "Homem Aranha 2",
    "Homem Aranha 3",
    "Sniper Americano",
    "Quarteto Fantástico",
    "Jurassic World: Mundo dos Dinossauros",
    "O Atirador",
    "Ressaca de Amor",
    "Anjos da Lei 2",
    "Capitão America: Guerra Civil",
    "Capitão America: O Primeiro Vingador",
    "Guerra Mundial Z",
    "Vingadores",
    "Madrugada dos Mortos",
    "Homem de Ferro 1",
    "Homem de Ferro 2",
    "Homem de Ferro 3",
    "Horas de Desespero",
    "Godzilla",
    "Cidade de Deus",
    "O Resgate do Soldado Ryan",
    "Sex Drive - Rumo ao Sexo",
    "Projeto X",
    "Guerra Ao Terror",
    "Jogos mortais 1",
    "Jogos mortais 2",
    "Jogos mortais 3",
    "Jogos mortais 4",
    "Jogos mortais 5",
    "Robocop",
    "Carga Explosiva 3",
    "Linha de Frente",
    "Os Especialistas",
    "Uma Saida de Mestre",
    "Terremoto: A Falha de San Andreas",
    "Hércules",
    "G.I Joe 2: Retaliação",
    "Operações Especiais",
    "Rapida Vingança",
    "Piranha 3D",
    "Invasão do mundo: Batalha em Los Angeles",
    "Expelled",
    "Kingsman: Serviço Secreto",
    "Arrume um Emprego",
    "Apenas duas noites",
    "Doce Veneno",
    "Superbad",
    "Show de vizinha",
    "O Nevoeiro",
    "Será Quê?",
    "Até o último homem",
    "Capitão Philips",
    "O Mínimo para Viver",
    "A 5ª Onda",
    "The Duff",
    "Em ritmo de fuga",
    "Mine",
    "Falcão negro em perigo",
    "O Cerco de Jadotville",
    "John Wick: De Volta ao Jogo",
    "De Volta ao Jogo 2",
    "Amizade Desfeita; Unfriend",
    "Truque de Mestre 1",
    "Círculo De Fogo",
    "Viagem ao Centro da Terra",
    "Chernobyl",
    "O Abutre",
    "Perigo em Alto Mar",
    "A Primeira vez",
    "As Vantagens de ser Invisível",
    "Ouija: Origem do Mal",
    "O Preço da Liberdade",
    "Zona Verde",
    "Busca sem Limites",
    "Assassino a Preço Fixo 2",
    "Os Mercenários 3",
    "Parker",
    "Hush: A Morte Ouve",
    "O homem mais procurado do Mundo",
    "A Cura",
    "Corra!",
    "Jogo Perigoso",
    "Deadpool",
    "Amor Rebelde",
    "Pânico na Ilha",
    "Area 51",
    "Assalto ao poder",
    "Pânico na Neve",
    "Um Limite Entre Nós",
    "O dia do atentado",
    "Encarcerado",
    "Arraste-me para o inferno",
    "Forças Especiais",
    "Assalto ao Banco Central",
    "The Inbetweeners Movie",
    "Zerando a Vida",
    "Road Trip: Caindo na Estrada",
    "Elysium",
    "O Ultimo Desafio",
    "Jogos Vorazes",
    "Jogos Vorazes: Em Chamas",
    "Jogos Vorazes: A Esperança Parte 1",
    "Jogos Vorazes: A Esperança O Final",
    "Jumper",
    "Rua Cloverfield",
    "Dose Dupla",
    "Dono Da Festa",
    "American Pie 1",
    "American Pie 2",
    "American Pie 3",
    "American Pie 4",
    "American Pie 5",
    "American Pie 6",
    "American Pie 7",
    "American Pie 8",
    "Dono da Festa 2",
    "Dono da Festa 3",
    "Riddick 3",
    "2012",
    "Quebrando a Banca",
    "Premonição 5",
    "Verão em State Island",
    "Sempre ao seu Lado",
    "O livro de Eli",
    "As Aventuras de Pi",
    "Homem de Aço",
    "Invocação do Mal 2",
    "Toy Story 1",
    "Toy Story 2",
    "Toy Story 3",
    "Monstros S.A",
    "Procurando Nemo",
    "O Pequeno Stuart Little (1999)",
    "O Pequeno Stuart Little 2",
    "Lilo & Stitch",
    "Carros 1",
    "Carros 2",
    "Dinossauro (2000)",
    "Dragon Ball: A Batalha dos Deuses",
    "Dragon Ball: O Renascimento de Freeza",
    "Fuga Das Galinhas",
    "Alvin e Os Esquilos",
    "Alvin e os Esquilos 2",
    "Vida de Inseto",
    "Os Incríveis",
    "Barbie: O Quebra Nozes (2001)",
    "Shrek",
    "Shrek 2",
    "O Rei Leão (1994)",
    "Os Cavaleiros do Zodiaco: Lenda Do Santuário",
    "Onde Está Segunda?",
    "O Homem Nas Trevas",
    "Horizone Profundo: Desastre No Golfo",
    "Perdido em Marte",
    "A Chegada",
    "Filha do Mal",
    "A Babá",
    "Quando As Luzes Se Apagam",
    "Anabelle",
    "Anabelle 2",
    "7 Desejos",
    "No Coração Do Mar",
    "O Quarto do Pânico",
    "1922",
    "A Visita",
    "A Síndrome De Berlin",
    "Fragmentado",
    "Armas na Mesa",
    "A Casa dos Mortos (2015)",
    "Quase 18",
    "Dupla Explosiva",
    "Golpe Duplo",
    "It: A Coisa",
    "Não Desligue",
    "Planeta dos Macacos: A Origem",
    "Dunkirk",
    "2:22 Encontro Marcado",
    "Dia de Trabalho Mortal",
    "Versões de Um Crime",
    "Amityville: O Despertar",
    "A Dama do Espelho: O Ritual das Trevas",
    "Todo Mundo em Pânico 3",
    "Além da Morte",
    "Assassinos Múltiplos",
    "Feito na América",
    "Man Down: A Guerra",
    "Criminosos de Novembro",
    "Tempestade: Planeta em Fúria",
    "A Morte Te Dá Parabéns",
    "O Assassino: O Primeiro Alvo",
    "Visita Noturna",
    "Luzes de Phoenix",
    "Fome de Poder",
    "O Estado das Coisas",
    "Holidays",
    "Quebrando Regras",
    "Quebrando Regras 2",
    "Thank You for Your Service",
    "Sobrenatural: Capítulo 2",
    "A Casa de Cera",
    "A Teoria de Tudo",
    "Mark Felt: O Homem que Derrubou a Casa Branca",
    "12 Heróis",
    "Sobrenatural: A Última Chave",
    "A Possessão do Mal",
    "Maze Runner: A Cura Mortal",
    "Paterno",
    "O Jogo da Imitação",
    "Um Olhar do Paraíso",
    "Medo Profundo",
    "Assim na Terra como no Inferno",
    "A Grande Jogada",
    "Scott Pilgrim Contra o Mundo",
    "O Sono da Morte",
    "Rebelde Com Causa",
    "Extraordinário",
    "Um Lugar Silencioso",
    "Rampage: Destruição Total",
    "Covil de Ladrões",
    "O Último Exorcismo",
    "O Lobo de Wall Street",
    "O Poderoso Chefão",
    "Lady Bird - A Hora de Voar",
    "O Contador",
    "Vizinhos 2",
    "American Ultra: Armados e Alucinados",
    "Verdade ou Desafio",
    "Vingadores: Guerra Infinita",
    "Desejo de Matar",
    "Jogador Nº 1",
    "A Vida em Espera",
    "A Barraca do Beijo",
    "Deadpool 2",
    "Pedido de Amizade",
    "22 de Julho",
    "Arranha-Céu: Coragem Sem Limite",
    "8 Mile - Rua das Ilusões",
    "Megatubarão",
    "O Ritual",
    "Jogos Mortais: Jigsaw",
    "O Protetor 2",
    "22 Milhas",
    "The Late Bloomer",
    "O Quarto de Jack",
    "A Freira",
    "A Primeira Noite de Crime",
    "Animais Fantásticos e Onde Habitam",
    "A Casa do Medo (2018)",
    "Vingança",
    "Caixa de Passáros (BirdBox)",
    "O Chamado 2",
    "A Escuridão",
    "Possessão",
    "A Casa do Medo - Incidente em Ghostland",
    "Corredor Assombrado",
    "Polar",
    "Operação Overlord",
    "Fúria em Alto Mar",
    "Loucura do Tempo",
    "Selvagem (2018)",
    "Cadáver",
    "Velocidade Mortal",
    "Amador",
    "Parque do Inferno",
    "O Culto",
    "Amizade Desfeita 2",
    "Satânico",
    "O Espelho",
    "Asfalto de Sangue",
    "Não Olhe",
    "Vingadores: Ultimato",
    "A Saga Crepúsculo: Crepúsculo",
    "A Saga Crepúsculo: Lua Nova",
    "A Saga Crepúsculo: Eclipse",
    "A Saga Crepúsculo: Amanhecer pt1",
    "A Saga Crepúsculo: Amanhecer pt2",
    "A Morte Te Dá Parabéns 2",
    "O Homem que Mudou o Jogo",
    "Death Note",
    "Festa da Salsicha",
    "O Discurso do Rei",
    "O Dono do Jogo",
    "El Camino",
    "A Forca 2",
    "Miss American",
    "Midway - Batalha em Alto Mar",
    "1917",
    "O Irlandês",
    "Cam",
    "A Grande Aposta",
    "Cães de Guerra",
    "O Poço",
    "Eu os Declaro Marido... e Larry",
    "A Missy Errada",
    "O Poderoso Chefão 2",
    "Gente Grande",
    "Heilstaten",
    "A Hora da Sua Morte",
    "Hereditário",
    "A Bruxa",
    "365 dni",
    "Altos Negócios",
    "Rede de Ódio",
    "Midsommar",
    "Garota Exemplar",
    "Kong: Ilha da Caveira",
    "Sully: O Herói do Rio Hudson",
    "O Culpado",
    "A Guerra do Amanhã",
    "Um Marido Fiel",
    "Era uma vez em Hollywood",
    "Clube da Luta",
    "A Batalha Esquecida",
    "Questão de Tempo",
    "Top Gun: Maverick",
    "Coringa",
    "John Wick 3",
    "Fratura",
    "O Grito",
    "Avatar",
    "Posto de Combate",
    "Ilha das Rosas",
    "Jurassic World: Dominio",
    "Nada de Novo no Front",
    "O Homem Invisível",
    "O Menu",
    "Oppenheimer",
    "Megatubaráo 2",
    "Gran Turismo",
    "Anônimo",
    "O Assassino",
    "A Baleia",
    "A Morte do Demônio",
    "X - A Marca da Morte",
    "Pearl",
    "O Rei",
    "Resgate",
    "Resgate 2",
    "Aniquilação",
    "Extinção",
    "Sicario: Terra de Ninguém",
    "Agente Oculto",
    "Planeta dos Macacos: ?",
    "Barbie",
    "Fale Comigo",
    "Mergulho Noturno",
    "O Telefone Preto",
    "Vida",
    "Escape Room",
    "Escape Room 2",
    "Ameaça Profunda",
    "Super Mario Bros",
    "Efeito Borboleta",
    "Beekeper: Rede de Vingança",
    "Corvo Branco",
    "Inatividade Paranormal",
    "Duna",
    "Bruxa de Blair (1999)",
    "Saltburn",
    "Sorria",
    "Um Lugar Silencioso 2",
    "Desespero Profundo",
    "Godzilla e Kong: Novo Império",
    "Pobres Criaturas",
    "Noite Passada em Soho",
    "The Batman",
    "Duna 2",
    "Herói por Encomenda",
    "O Amor É Cego",
    "Alerta Vermelho",
    "Fresh",
    "Um Lugar Bem Longe Daqui",
    "O Pacto",
    "A Freira 2",
    "Godzilla Minus One",
    "AIR: A História do Logo",
    "REC",
    "Sob As Águas do Sena",
    "Brilho Eterno de Uma Mente Sem Lembranças",
    "Divertidamente",
    "Maxxxine",
    "Durante a Tormenta",
    "Por Água Abaixo",
    "Invasão",
    "Alien Romulus",
    "Longlegs",
    // Adicione mais filmes conforme necessário
  ];

  const tmdbApiKey = "88740fcede037c6631f0d94c508f0454"; // Substitua pela sua chave real
  const omdbApiKey = "3d49971e"; // Substitua pela sua chave real
  const filmesProcessados = []; // Array que armazenará os filmes processados

  for (const titulo of filmes) {
    try {
      const { title, originalTitle, overview, posterPath } = await tmdbApi(titulo, tmdbApiKey);
      const movieDetails = await omdbApi(originalTitle, omdbApiKey);
      const movieData = { ...movieDetails, overview, posterPath, title };

      // Adicione o filme processado ao array
      filmesProcessados.push(movieData);
      console.log(`Filme ${title} adicionado com sucesso.`);
    } catch (error) {
      console.error(`Erro ao adicionar o filme ${titulo}:`, error);
    }
  }

  // Retorne o array de filmes processados
  return filmesProcessados;
};

export default processarLote;
